# Generated by Django 2.2.4 on 2019-10-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuchoice',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='lunch_tracker.Customer'),
        ),
        migrations.AlterField(
            model_name='menuchoice',
            name='meal_name',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='lunch_tracker.Meal'),
        ),
    ]
